# Generated by Django 4.2.16 on 2024-10-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acolchados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('composicion', models.CharField(max_length=20)),
            ],
        ),
    ]
