# Generated by Django 4.2.16 on 2024-10-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comienzo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acolchados',
            name='tamanio',
            field=models.CharField(choices=[('twin', 'Twin'), ('queen', 'Queen'), ('king', 'King')], max_length=10, verbose_name='tamaño'),
        ),
    ]
