# Generated by Django 4.2.16 on 2024-11-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comienzo', '0002_alter_acolchados_tamanio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acolchados',
        ),
    ]
