# Generated by Django 4.2.16 on 2024-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frazada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', models.CharField(choices=[('twin', 'Twin'), ('queen', 'Queen'), ('king', 'King')], max_length=10, verbose_name='tamaño')),
                ('color', models.CharField(max_length=20)),
                ('estilo', models.CharField(choices=[('liso', 'Liso'), ('rústico', 'Rústico'), ('estampado', 'Estampado')], max_length=10)),
                ('fecha_fabricacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', models.CharField(choices=[('twin', 'Twin'), ('queen', 'Queen'), ('king', 'King')], max_length=10, verbose_name='tamaño')),
                ('color', models.CharField(max_length=20)),
                ('composicion', models.CharField(max_length=20)),
                ('hilos', models.IntegerField()),
                ('fecha_fabricacion', models.DateField()),
            ],
        ),
    ]
