# Generated by Django 4.2.16 on 2024-11-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acolchados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', models.CharField(choices=[('twin', 'Twin'), ('queen', 'Queen'), ('king', 'King')], max_length=10, verbose_name='tamaño')),
                ('color', models.CharField(max_length=20)),
                ('composicion', models.CharField(max_length=20)),
            ],
        ),
    ]
