# Generated by Django 4.2.16 on 2024-11-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_acolchados'),
    ]

    operations = [
        migrations.AddField(
            model_name='acolchados',
            name='fecha_fabricacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación'),
        ),
        migrations.AddField(
            model_name='acolchados',
            name='imagen_acolchado',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='frazada',
            name='imagen_frazada',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='sabana',
            name='imagen_sabana',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='acolchados',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='acolchados',
            name='composicion',
            field=models.CharField(max_length=20, verbose_name='Composición'),
        ),
        migrations.AlterField(
            model_name='acolchados',
            name='tamanio',
            field=models.CharField(choices=[('twin', 'Twin'), ('queen', 'Queen'), ('king', 'King')], max_length=10, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='frazada',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='frazada',
            name='estilo',
            field=models.CharField(choices=[('liso', 'Liso'), ('rústico', 'Rústico'), ('estampado', 'Estampado')], max_length=10, verbose_name='Estilo'),
        ),
        migrations.AlterField(
            model_name='frazada',
            name='fecha_fabricacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación'),
        ),
        migrations.AlterField(
            model_name='frazada',
            name='tamanio',
            field=models.CharField(choices=[('twin', 'Twin'), ('queen', 'Queen'), ('king', 'King')], max_length=10, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='sabana',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='sabana',
            name='composicion',
            field=models.CharField(max_length=20, verbose_name='Composición'),
        ),
        migrations.AlterField(
            model_name='sabana',
            name='fecha_fabricacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación'),
        ),
        migrations.AlterField(
            model_name='sabana',
            name='hilos',
            field=models.IntegerField(verbose_name='Hilos'),
        ),
        migrations.AlterField(
            model_name='sabana',
            name='tamanio',
            field=models.CharField(choices=[('twin', 'Twin'), ('queen', 'Queen'), ('king', 'King')], max_length=10, verbose_name='Tamaño'),
        ),
    ]
